# Generated by Django 2.0.4 on 2018-06-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userquestion', models.CharField(max_length=64)),
                ('question_time', models.CharField(max_length=64)),
            ],
        ),
    ]
