# Generated by Django 2.0.7 on 2018-08-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QAManagement', '0004_auto_20180829_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioncount',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usermining',
            options={'managed': False},
        ),
    ]
