# Generated by Django 2.0.7 on 2018-08-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QAManagement', '0005_auto_20180829_2334'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questioncount',
            table='QAManagement_questioncount',
        ),
        migrations.AlterModelTable(
            name='user',
            table='QAManagement_user',
        ),
        migrations.AlterModelTable(
            name='usermining',
            table='QAManagement_usermining',
        ),
    ]
